# Generated by Django 5.2 on 2025-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(default=None, upload_to='produk_images/'),
            preserve_default=False,
        ),
    ]
