# Generated by Django 5.2 on 2025-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_produk_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk_images/'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
