# Generated by Django 5.2 on 2025-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nama_pengeluaran', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
