# Generated by Django 5.2.1 on 2025-06-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0001_initial'),
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alamat',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.customer')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.produk')),
            ],
        ),
    ]
