# Generated by Django 5.2.1 on 2025-06-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0002_alter_customer_alamat_transaksi'),
        ('kasir', '0003_auto_add_closing_fields'),
    ]

    operations = [
    ]
