# Generated by Django 5.2.1 on 2025-06-15 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_itemtransaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransaksi',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemtransaksi',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.transaksi'),
        ),
    ]
