# Generated by Django 5.2.1 on 2025-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0004_merge_20250624_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closing',
            name='customer',
        ),
        migrations.AlterField(
            model_name='closing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
