# Generated by Django 5.2.1 on 2025-06-15 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0004_alter_itemtransaksi_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='produk',
        ),
        migrations.AlterField(
            model_name='itemtransaksi',
            name='jumlah',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemtransaksi',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemtransaksi',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kasir.transaksi'),
        ),
    ]
