# Generated by Django 5.2.1 on 2025-06-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0005_remove_closing_customer_alter_closing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closing',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kasir.customer'),
        ),
    ]
