# Generated by Django 5.2.1 on 2025-06-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0007_closing_tanggal'),
    ]

    operations = [
    ]
