# Generated by Django 5.2.1 on 2025-05-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(null=True, upload_to='produk/')),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pengeluaran Umum', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),  # Change to DateTimeField for better tracking
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),  # Add amount field
                ('payment_status', models.CharField(
                    max_length=20,
                    choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')],
                    default='unpaid'
                )),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.kategori')),
            ],
        ),
    ]