# Generated by Django 5.2.1 on 2025-06-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengeluaran',
            old_name='jumlah',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='pengeluaran',
            old_name='tanggal',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='pengeluaran',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='pengeluaran',
            name='nama',
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
    ]
