# Generated by Django 5.2.1 on 2025-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [


        migrations.AlterField(
            model_name='pengeluaran',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pengeluaran',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
