# Generated by Django 5.2.1 on 2025-06-05 07:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengeluaran',
            name='tanggal',
        ),
        migrations.RemoveField(
            model_name='pengeluaran',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='pengeluaran',
            name='nama',
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='amount',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='category',
            field=models.ForeignKey(to='gudang.Kategori', on_delete=models.SET_NULL, null=True),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]