# Generated by Django 5.2.1 on 2025-06-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0002_remove_pengeluaran_kategori_pengeluaran_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengeluaran',
            name='kategori',
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
    ]
