# Generated by Django 5.2.1 on 2025-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0002_rename_jumlah_pengeluaran_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengeluaran',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
    ]
