# Generated by Django 5.2.1 on 2025-07-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0003_remove_pengeluaran_kategori_pengeluaran_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengeluaran',
            options={'ordering': ['-date']},
        ),
    ]
