# Generated by Django 5.2.1 on 2025-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudang', '0004_alter_pengeluaran_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengeluaran',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
